### ISSUE TITLE
Crop picture from user upload

### ISSUE THREAD

**Issue by ulissesferreira** [upframe/upframe.io#102]

**Comment by SwenSchaeferjohann** [comment]
![inkedscreenshot 1 test_li](https://user-images.githubusercontent.com/42959314/51677788-01341480-1fdb-11e9-9d59-e388466aa6b9.jpg)

This is what happens if the profile photo is not cropped into the square format-see screenshot.

**Comment by SwenSchaeferjohann** [comment]
Even though it looks  akward - non-prio for first release, since it doesn't break the tool. 
One of the first UX fixes that we should tackle once more essential stuff is solved.

**Comment by ulissesferreira** [comment]
Just made sure this was already fixed using styling. Picture uploaded maintain their aspect ratio and adapt to the content box. No need to crop pictures unless we decide to prettify the user upload. I'm closing this issue since that behaviour is gone.
