### ISSUE TITLE
Settings - Public Tab - User wants to be able to use ENTER  to move to next text box

### ISSUE THREAD

**Issue by ulissesferreira** [upframe/upframe.io#104]

**Comment by SwenSchaeferjohann** [comment]
Space or Enter key? 👯‍♂️

**Comment by ulissesferreira** [comment]
I belive enter makes more sense. Fields can have spaces...

**Comment by SwenSchaeferjohann** [comment]
non prio for first release, let's keep this little feature in mind for future tho!
