### ISSUE TITLE
Skeleton Loading

### ISSUE THREAD

**Issue by fabiofcferreira** [upframe/upframe.io#109]
Currently, we have a loading animation but that's not as good as it can get. Both app performance and app perceived performance are important, so I suggest adding skeleton loading in order to improve user overall experience.

Related to #43

**Comment by ulissesferreira** [comment]
This will be a nice to have. But let's get a spinning wheel for the next release ASAP. We want mentors onboard.

**Comment by malikpiara** [comment]
No.
