### ISSUE TITLE
Global state management

### ISSUE THREAD

**Issue by ulissesferreira** [upframe/upframe.io#111]
We are doing a lot of API operations twice which is completely unnecessary. The way we can fix a lot of weird behaviour in Connect is by using a global state manager. Right now React has an awesome Context API that will make everything easier but we could also use Redux, Mobx or Unstated. We should go with the Context API because it will not increase bundle size.

Make sure that we follow the Flux architecture.

**Comment by ulissesferreira** [comment]
The barebones for this issue are already finished we just need to optimize the rest of the app to efficiently utilize this method instead of requests to the API.

**Comment by SwenSchaeferjohann** [comment]
@ulissesferreira Is this essential for our first release (I'd be eternally grateful if you explain this thing to me, a newbie 😁 )

**Comment by fabiofcferreira** [comment]
Currently, we are using one React feature called Context API, which basically wraps the whole application and gives access to a global variable for all components (Navbar, Mentor Card, you name it). We need to do some revision of the written code but I am not sure whether this should really be the priority for now.

**Comment by SwenSchaeferjohann** [comment]
I see, thanks for explaining! 👍 Let's remove the priority label for now and revisit once we released our first version!

**Comment by ulissesferreira** [comment]
This is already implemented. If some of the optimizations are missing I will add them to specific issues instead of this general one 😄
