### ISSUE TITLE
Limit text fields correctly: reopen

### ISSUE THREAD

**Issue by SwenSchaeferjohann** [upframe/upframe.io#112]
Citing Ulisses: 
_"Right now if we surpass our DB's field limit the program will not crash nor will it ever display a error. What happens next is that the saved information is incomplete and may even break the website! An example of this is when you add too much expertise tags and thanks to the stringify method they are saved in a specific format. If this information is too big then when we return it to our frontend, JSON.parse() will fail and crash the whole interaction (You can successfully replicate this. Just add a lot of expertise tags).
Due to the fact that this is an app breaking bug I believe it has high priority."_

This still happens when creating more than 7 expertise tags: We need to limit these aswell.

**Comment by fabiofcferreira** [comment]
I guess that's supposed to, because Ulisses changed the limit to 7 tags.

**Comment by SwenSchaeferjohann** [comment]
Yep, though the site breaks silently if one creates more than 7 (which is still possible to do).

**Comment by ulissesferreira** [comment]
It's not about the number seven, it's more about the size of all the tags combined and stringified. Let's set a low limit (3 tags) and make char count to prevent this. This and favorite locations are the only inputs not limited yet I believe

**Comment by fabiofcferreira** [comment]
I guess we should create an alternative as soon as possible as this JSON handling is not the way to go. I'm creating a feature branch right now. @ulissesferreira

**Comment by ulissesferreira** [comment]
Not sure if that's a priority mate but do as you please @fabiofcferreira. I will be busy studying for exams. Most of the stuff is fixed but we do have some weird bugs that make the beta unusable for our mentors. I would try to have something nice for them ASAP and then work on improvements. But again, I trust your judgement

**Comment by ulissesferreira** [comment]
Talk to Malik if you can. Also if you could investigate #113 it would be cool 😮 everything is configured correctly but there was a file that I could upload (4,6 MB) that now fails with a weird CORS excuse...

**Comment by SwenSchaeferjohann** [comment]
Even though it breaks stuff in edge cases, we consider it non-priority for our first release. Why? Because scheduling events is the test objective for now - In the rare case that mentors troll and add too many skill tags (which is yet another feature) we can clean up the database manually.
At a later stage this will become a essential issue though, let's keep it in the backlog.
