### ISSUE TITLE
Some file uploads fail without explanation

### ISSUE THREAD

**Issue by ulissesferreira** [upframe/upframe.io#113]
Only clue we have is no CORS header but it only happens with some pictures

**Comment by ulissesferreira** [comment]
More details, even though upload "fails" it most of the times actually succeeds. I believe this is related to #111 being a work in progress yet. Once we finish its implementtion all the weird errors will disappear. Whatsmore I also believe big files are failing due to the fact that we are not settings a time limit for the uploads and the default is timing out. Needs more experimentation

**Comment by fabiofcferreira** [comment]
Fixed in https://github.com/upframe/api/commit/a6759b413acde13cdfafe86a8381db0fcd84482f
