### ISSUE TITLE
Make the location info a required field for the mentor.

### ISSUE THREAD

**Issue by SwenSchaeferjohann** [upframe/upframe.io#117]
What do u think how much effort would that issue be?

After all, I think this would be good to don't break our forms if mentors don't fill info, **but** it is non-priority for our first release I assume. 
Let's just keep it in mind and backlog. (location yet another feature.)

**Comment by malikpiara** [comment]
<img width="876" alt="screen shot 2019-01-30 at 18 19 55" src="https://user-images.githubusercontent.com/6923650/51999755-bf640c00-24bb-11e9-91a5-690cf0addab3.png">

**Comment by ulissesferreira** [comment]
Just fixed this making it impossible for people to add just empty space. It is not the most sophisticated heuristic but it will do as an MVP. We may look forward to a Google Maps feature, who knows, but that's not for now 😄
