### ISSUE TITLE
Navbar - Clicking bug

### ISSUE THREAD

**Issue by ulissesferreira** [upframe/upframe.io#122]
Upon clicking anywhere in the navbar it doesn't close. We need this fixed. Also when we click outside of the navbar it should close without doing anything.

**Comment by malikpiara** [comment]
@ulissesferreira Can you elaborate? Are you talking about the options users are given when they click on their profile picture? How long does it take to solve?

**Comment by fabiofcferreira** [comment]
Very fast. It's just 3 lines of JS.

**Comment by fabiofcferreira** [comment]
This is intended and yes, it is in fact the user menu that is opened every time you click on your profile pic in the navbar. Should we change it to automatic close when user clicks anything but the menu items? @malikpiara

**Comment by SwenSchaeferjohann** [comment]
Let's not touch it until we solved the more pressing issues

**Comment by malikpiara** [comment]
Yes
