### ISSUE TITLE
All — Update page when user logs out

### ISSUE THREAD

**Issue by malikpiara** [upframe/upframe.io#123]
When the user clicks on logout the page is not 
<img width="876" alt="screen shot 2019-01-30 at 18 19 55" src="https://user-images.githubusercontent.com/6923650/52000527-a4929700-24bd-11e9-85b6-4517f03439d6.png">
updated

**Comment by malikpiara** [comment]
Not essential @fabiofcferreira but let me know how long it takes for you to solve this.

**Comment by fabiofcferreira** [comment]
Quickly.

**Comment by SwenSchaeferjohann** [comment]
xDDDDD
