### ISSUE TITLE
Navbar - Fix lightbox and z-index

### ISSUE THREAD

**Issue by malikpiara** [upframe/upframe.io#127]
<img width="1440" alt="screen shot 2019-02-01 at 15 48 03" src="https://user-images.githubusercontent.com/6923650/52129859-f14ead00-2638-11e9-82f8-cb2f9cc28318.png">

Should be like this instead:

<img width="1440" alt="screen shot 2019-02-01 at 15 49 31" src="https://user-images.githubusercontent.com/6923650/52129884-00cdf600-2639-11e9-8280-e6f04961dcbd.png">

And when you click outside the window/box you should be able to exit.

**Comment by SwenSchaeferjohann** [comment]
Why should it be so? Isn't it disconnecting the user from the site even more?
EDIT: declutters and is more focussed right now. good point malik! 👍

**Comment by fabiofcferreira** [comment]
It has been already fixed I guess.
