### ISSUE TITLE
Calendar sync - after sync redirection

### ISSUE THREAD

**Issue by SwenSchaeferjohann** [upframe/upframe.io#130]
Right now, after syncing ones calendar the first time, the user is being redirected **out** of the calendar tab back into the settings/profile tab. 
When onboarding for the first time, this screws people off: We need to land them safely back where they'd left for the sync...
@ulissesferreira @fabiofcferreira How much work is that ish?

**Comment by ulissesferreira** [comment]
We should change the routing of the settings so that we have a bigger control over where the user is taken. We should have /settings/public + /settings/account + /settings/sync
