### ISSUE TITLE
Sync - Preliminary UX fix 

### ISSUE THREAD

**Issue by SwenSchaeferjohann** [upframe/upframe.io#131]
**Important Read:** 
In order to not screw people off at their first usage, we need small fixes to the UX.

These are meant to 
A) Signal how to create free time slots (grey "save slots" button - people might deduct from that that they should create slots in the calendar)
B) Make sure that slots are being safed (big fat red button change)
while not consuming too much development effort (@ulissesferreira @fabiofcferreira  - examine and give feedback pls.)

- the button should be fixed in position regardless of scrolling, so that people actually find the button even if the create a slot at "11pm".
Here's 2 screenshots of it: (Note that only the button matters right now, rest is meant as placeholder!)
Before having created at least one slot:
![image](https://user-images.githubusercontent.com/42959314/52166301-ced99400-270b-11e9-88fd-2b50bc0ebab4.png)

After having created at least one slot:
![image](https://user-images.githubusercontent.com/42959314/52166304-d9942900-270b-11e9-8565-a2d0bdd82600.png)

These designs are preliminary only, and we will have to come up with a more fulfilling experience soonish. @malikpiara @SwenSchaeferjohann

**Comment by SwenSchaeferjohann** [comment]
reopened:
- styling of "(un)link google" btn can be removed, it should not take much of their attention
- "Save slots" btn should A) be fixed in position (see post above) B) take the "grey" style before there's any new slot created and change to red only after one new slot had been created.

Right now it looks like this -
![image](https://user-images.githubusercontent.com/42959314/52177277-cee69c00-27be-11e9-8fbc-c967fba8b633.png)

![image](https://user-images.githubusercontent.com/42959314/52177281-dad25e00-27be-11e9-9689-236637e74eb3.png)

![image](https://user-images.githubusercontent.com/42959314/52177285-e58cf300-27be-11e9-8b57-fcd4acf7228c.png)

**Comment by SwenSchaeferjohann** [comment]
@fabiofcferreira @ulissesferreira 
Do you guys think it's feasible to make the 'save slots' button fixed in position while scrolling?
What needs to be changed there? I'm curious!

**Comment by fabiofcferreira** [comment]
I completely forgot to leave a comment here. For now, this issue is fixed. The button is halfway across the calendar. Since this is just an alpha release for our mentors to start using and testing I guess we can close this and invest in a better design system.
