### ISSUE TITLE
Add all slots to Google Calendar

### ISSUE THREAD

**Issue by fabiofcferreira** [upframe/upframe.io#137]
Currently, only the meetings are sent and saved in mentor's google calendar.

This issue aims to solve that problem. By implementing the sending of all slots and all meetings to Google Calendar, mentors can always check their free timeslots there instead of continuously logging into our platform to do so.

**Comment by SwenSchaeferjohann** [comment]
Out of curiosity
; how is that achieved?

**Comment by ulissesferreira** [comment]
@SwenSchaeferjohann Basically it's the same way we add the meetups :D Whenever the user clicks on save slots we can send this information to the Google API using the token we get from the syncing part. That token is like our key to access all the services provided by Google and do things as if we were the user.

**Comment by SwenSchaeferjohann** [comment]
got it. How much workload would u think is it?
