### ISSUE TITLE
Replacing Time slot event with scheduled event

### ISSUE THREAD

**Issue by SwenSchaeferjohann** [upframe/upframe.io#138]
**This follows up on #137 **
Once a meeting has been scheduled, we need to replace the 'free time-slot event' with a 'Meeting event'.
Therein should be the necessary info:
- with whom
- location
- topic(is that possible? @fabiofcferreira )

**Comment by SwenSchaeferjohann** [comment]
How would you approach this issue?

**Comment by fabiofcferreira** [comment]
We are using an NPM package called googleapis which lets us use each mentor's Google API access token to perform any type of action we need (create, update and delete events).
