### ISSUE TITLE
Warn users if they try to leave without saving information

### ISSUE THREAD

**Issue by ulissesferreira** [upframe/upframe.io#139]
We need to warn our users if they try to leave the website without saving their user information. A simple alert will do

**Comment by SwenSchaeferjohann** [comment]
shouldn't take more than 5 minutes right?

**Comment by fabiofcferreira** [comment]
More or less yeah. I'm gonna solve that ASAP as that provides mentors with better experience.

**Comment by ulissesferreira** [comment]
This is basically fixed at branch feat/autosaving. All we have to do is create a PR and merge 😄
