### ISSUE TITLE
Free slot deletion error but successful

### ISSUE THREAD

**Issue by ulissesferreira** [upframe/upframe.io#142]
For some reason (probably Service Worker caching) our free slots when deleted sometimes bug out and display an error. This error says that the free slot could not be deleted. However, once we check our mentor page we clearly see that it was successfully deleted. They keep showing in the Settings Sync tab however they don't appear on our mentor page.

**Comment by ulissesferreira** [comment]
After deleting the service worker the free slots keep showing on the Settings Sync tab. This also happens when using Incognito mode

**Comment by SwenSchaeferjohann** [comment]
🤔

**Comment by ulissesferreira** [comment]
After some investigation basically what is happening here is a miscomunication between Google Calendar slots and our stored slots. If one of the deletions fails then everything bugs out and an error message is produced. Example scenario: you delete one of the slots on Google using the calendar. When our API tries to go and delete it in Google, it fails [since that's already been done] and does not allow deletion of the slot on our own DB. I believe we need to switch our strategy to a "Best Effort" one. We use our API as the single source of truth and we do not take Google Calendar errors seriously

**Comment by ulissesferreira** [comment]
And to complement this we can sometimes make a "sync" and send our slots over there to make sure everything is ok. But basically allow people to delete stuff on Google and not worry about it.

**Comment by ulissesferreira** [comment]
Which means errors will only be directed towards our own slots. If we get an error message is because we failed to delete in OUR backend and not Google

**Comment by ulissesferreira** [comment]
This is now fixed. Our Google Calendar sync is working as a best effort. Things are done on the background and it's normal if it takes some time to sync everything up there. The same happens for deletion and addition. You delete slots and it is normal it takes a while for all the changes to happen but don't worry, they eventually happen 😄 This is on Google, we can't really improve their speed. There are some optimizations we can do but those are for later (for example if two slots are close to one another we can turn them into one)
