### ISSUE TITLE
Automatic division of big slots sometimes fails

### ISSUE THREAD

**Issue by ulissesferreira** [upframe/upframe.io#145]
![randomfreeslotsdisappearbug](https://user-images.githubusercontent.com/15613644/53520750-49f55680-3ace-11e9-9fc8-2db2305224fd.PNG)

The free slot was made with a drag from the top arrow to the bottom arrow and as you can see, one of the hours in the middle suddenly disapeared. This problem is located in the API.

**Comment by malikpiara** [comment]
I wonder if this is somehow related with the 'auto-save'.

**Comment by ulissesferreira** [comment]
It's not. It was already happening before. Auto save is nothing but a glorified automatic save button. Most of the bugs that poped up are actually related to the fact that we changed stuff in the API to add free slots to Google Calendar. This one is specific to the way we divide time and has been happening for quite a while.

**Comment by ulissesferreira** [comment]
[Update] I know why this is happening. I just witnessed it first hand, the free slots are added to the database however for some reason one of them gets randomly assigned a different Mentor ID so it's being added to another mentor. I am still investigating why this happens.

**Comment by ulissesferreira** [comment]
*[Update]* Problem located. Basically here it is:
![image](https://user-images.githubusercontent.com/15613644/53685413-39cdb900-3d12-11e9-8558-4445408b7087.png)

Our insert slots function is looking for slots that start and end at the same team. The idea was that we would stop mentors from adding the same slot on repeat. What's missing is making sure that we only verify this against the same mentor otherwise no mentor can add a free slot equal to another mentor 😂

**Comment by ulissesferreira** [comment]
Problem fixed by adding the following: 
![image](https://user-images.githubusercontent.com/15613644/53685454-bf516900-3d12-11e9-8c72-3259d01e7d1b.png)
