### ISSUE TITLE
Meetup confirmation works but displays error

### ISSUE THREAD

**Issue by ulissesferreira** [upframe/upframe.io#147]
Sometimes the mentor will click on the confirm link and receive an alert warning that we could not confirm said meetup. However the meetup was successfuly canceled and the user receives a confirm message.

**Comment by SwenSchaeferjohann** [comment]
Interesting... Anyone an idea why that could be?
(I'll test it more rigorously tomorrow)

**Comment by ulissesferreira** [comment]
Nope, no idea. I'm not looking at code yet, just collecting more bugs. When I finish testing all I will investigate 🧐

**Comment by ulissesferreira** [comment]
Some more details: it seems that the reason this happens is because the user receives the email with the confirmation but the mentor does not get the meetup added to his Google Calendar which means that part of the process is failing, but another part of it still works. Gonna take a look at code now.

**Comment by SwenSchaeferjohann** [comment]
Thrilled to hear about ur findings! @ulissesferreira

**Comment by ulissesferreira** [comment]
I believe this is fixed. Closing for now.
