### ISSUE TITLE
Firefox SVG Logo bad image quality

### ISSUE THREAD

**Issue by ulissesferreira** [upframe/upframe.io#148]
![firefox](https://user-images.githubusercontent.com/15613644/53524591-baed3c00-3ad7-11e9-8f04-cddbcdbc7dee.PNG)

For some reason the SVG displayed with our beautiful logo has very poor quality 😞

**Comment by fabiofcferreira** [comment]
This could be a problem with Firefox itself and apparently the only thing we can do, is save the SVG as a less detailed SVG file.

**Comment by ulissesferreira** [comment]
@malikpiara Let's get this with a lower resolution then and try to see what happens

**Comment by malikpiara** [comment]
Is this still a thing? 😱

**Comment by ulissesferreira** [comment]
How are we here @malikpiara ?
