### ISSUE TITLE
Unlinking Google does not delete Upframe's Calendar

### ISSUE THREAD

**Issue by ulissesferreira** [upframe/upframe.io#150]
We should warn people that doing so will remove all the information they have regarding meetups and free slots but it does not make sense to leave the Calendar behind... Or does it? We can also make a case against since people can delete it anytime they want... Need input from @SwenSchaeferjohann and @malikpiara

**Comment by SwenSchaeferjohann** [comment]
def in backlog but not priority at all r n

**Comment by SwenSchaeferjohann** [comment]
People wont link their calendars that often.. Especially as long as we're having close to zero users, we should try to get the core hypothesis right before polishing it.

**Comment by malikpiara** [comment]
Not a priority.

**Comment by ulissesferreira** [comment]
Closing the issue due to no clear answer. Let's get some users on the platform and then understand what would be their preferred behaviour
