### ISSUE TITLE
Save Changes button not aligned on calendar page

### ISSUE THREAD

**Issue by malikpiara** [upframe/upframe.io#154]
<img width="1440" alt="screen shot 2019-03-03 at 23 33 16" src="https://user-images.githubusercontent.com/6923650/53704718-805d0980-3e1f-11e9-803a-14a1228fbf58.png">

The button should be exactly aligned with the same widget on the public profile settings. In case of doubt double check with me!

**Comment by malikpiara** [comment]
Can we take care of this until tomorrow? @ulissesferreira @fabiofcferreira

**Comment by fabiofcferreira** [comment]
I don't understand what you're asking here to be honest.

**Comment by malikpiara** [comment]
@fabiofcferreira The 'Save Changes' button should be in the same exact position in every page. It should also be aligned with the grid.

<img width="1440" alt="Screen Shot 2019-03-11 at 14 47 01" src="https://user-images.githubusercontent.com/6923650/54128526-92850c00-440c-11e9-9a7c-6a0bd866f52e.png">
<img width="1440" alt="Screen Shot 2019-03-11 at 14 46 54" src="https://user-images.githubusercontent.com/6923650/54128527-931da280-440c-11e9-864f-e7fc5a4c1031.png">

**Comment by fabiofcferreira** [comment]
Much clearer now. Will get to work, thanks.

**Comment by fabiofcferreira** [comment]
Fixed in 3cea051

**Comment by malikpiara** [comment]
Can we make it so that the button is aligned with the other elements above?

<img width="90" alt="Screen Shot 2019-03-11 at 19 07 56" src="https://user-images.githubusercontent.com/6923650/54146793-09cc9700-4431-11e9-8ee5-1a9bc288bb8a.png">

**Comment by ulissesferreira** [comment]
This will be a little tough due to the way CSS is organized now. I'll see what I can do but here's why #135 was so important even though not a priority. Some stuff is not easily maintainable :D

**Comment by fabiofcferreira** [comment]
It's not about maintainability, it's just that it's not that easy to make the button aligned to those fields in all screens.
