### ISSUE TITLE
Font optimizations

### ISSUE THREAD

**Issue by ulissesferreira** [upframe/upframe.io#158]
By using Poppins we removed font optimizations like preconnect. There is a ton of little neat tricks we can use. Read this:

- https://medium.com/clio-calliope/making-google-fonts-faster-aadf3c02a36d
- https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/webfont-optimization?hl=pt

And implement 😄

**Comment by malikpiara** [comment]
Is this still relevant or should we close the issue? @ulissesferreira
