### ISSUE TITLE
Add metadata information to the profiles

### ISSUE THREAD

**Issue by malikpiara** [upframe/upframe.io#166]
<img width="525" alt="Captura de ecrã 2019-07-04, às 09 55 21" src="https://user-images.githubusercontent.com/6923650/60649243-f4490600-9e41-11e9-98b1-e0577021fa69.png">

When someone shares a profile on social media or elsewhere, no metadata is passed on. Can we change that so that the name and description correspond to the name of a user and his/her description.

- [x] Add metaname
- [x] Add metadescription
- [x] Change title of each user page from 'Upframe' to 'Name of User | Upframe'

**Comment by fabiofcferreira** [comment]
Strange that we don't have that yet. However, I'll do it asap (next ~45m)

**Comment by fabiofcferreira** [comment]
Solved in recent commits (made yesterday).
