### ISSUE TITLE
Mentor gets broken when not refreshed properly

### ISSUE THREAD

**Issue by malikpiara** [upframe/upframe.io#167]
<img width="1145" alt="Captura de ecrã 2019-07-04, às 15 23 34" src="https://user-images.githubusercontent.com/6923650/60669935-ced2f100-9e6f-11e9-81c6-6f0cd41d870b.png">

Can't exactly pinpoint what's going on. – I noticed that when I share my profile (https://connect.upframe.io/malikpiara) sometimes, the profile information is not displayed when a user goes to the URL (see screenshot). I think this is related with interrupted requests. Try reloading the page once and then once again while the page is still reloading.

**Comment by fabiofcferreira** [comment]
I cannot replicate the issue you're having. It could be due to the updates I'm doing to the platform although I doubt it.
