### ISSUE TITLE
Requesting slots from a mentor should inform him of the person's email

### ISSUE THREAD

**Issue by ulissesferreira** [upframe/upframe.io#168]
I just received a request to add more slots to my profile and all I could read was a message and a name. It's very weird for me as a mentor to get asked about my time without even knowing who I am speaking with. 

Implement a new format where the mentor gets access to the 'requestees' email so they can chat directly.

**Comment by malikpiara** [comment]
Hurray! Could you share more info on Slack?

**Comment by ulissesferreira** [comment]
Check your telegram friend @malikpiara

**Comment by malikpiara** [comment]
@ulissesferreira @fabiofcferreira Please let me look into this before implementing a solution.

**Comment by malikpiara** [comment]
Not solved.

**Comment by malikpiara** [comment]
@ulissesferreira @fabiofcferreira Our user [Pedro Esperança](https://upframe.io/pedro.esperanca) suggested we **add the mentee's email in CC** so that they can communicate. It's a simple and very effective solution for now. I trust you to take care of it :)
