### ISSUE TITLE
Fix accept invitation button link

### ISSUE THREAD

**Issue by malikpiara** [upframe/upframe.io#169]
![Captura de ecrã 2019-07-05, às 09 43 22](https://user-images.githubusercontent.com/6923650/60706259-5d478100-9f09-11e9-9fd4-d0c5575480dc.png)

The 'Accept Invitation' button is hyperlinked to `https://beta.upframe.io/meetup/confirm/t4da2e96393a13c555e6ce9387452bb34e0590f99` instead of `https://connect.upframe.io/meetup/confirm/t4da2e96393a13c555e6ce9387452bb34e0590f99`

I had trouble accepting invitations because I'm not logged in at Beta.

**Comment by fabiofcferreira** [comment]
Fixed in upframe/api@e909f45
