### ISSUE TITLE
Free slots are defaulting to mobile size when they shouldn't

### ISSUE THREAD

**Issue by malikpiara** [upframe/upframe.io#170]
<img width="1244" alt="image" src="https://user-images.githubusercontent.com/6923650/60706625-29209000-9f0a-11e9-9b09-f548e06b5058.png">

As you can see on the screen the free slot containers are occupying the whole section for some unexplained reason. My screen size is 1337x1155.

**Comment by fabiofcferreira** [comment]
Cannot replicate. That must be a cache or CSS problem that occurred just in your machine. I'm closing this issue as I am highly confident that this is not the case of a bug.

**Comment by malikpiara** [comment]
Tried in different machines and different browsers. The bug is there @fabiofcferreira
