### ISSUE TITLE
Can we make upframe.io and www.upframe.io an ALIAS?

### ISSUE THREAD

**Issue by malikpiara** [upframe/upframe.io#171]
I can sense people are visiting upframe.io. Right now they're seeing the startup weekend page. It makes more sense to make our main domain an alias of connect so that **connect.upframe.io/ulisses** = **upframe.io/ulisses**?

It is important that upframe.io remains an ALIAS and not the real deal so we can make changes to the main domain in the future if we need to.

**Comment by fabiofcferreira** [comment]
Done with Cloudflare. 😄
