### ISSUE TITLE
Fixing mentor card containers on Firefox

### ISSUE THREAD

**Issue by malikpiara** [upframe/upframe.io#172]
<img width="839" alt="image" src="https://user-images.githubusercontent.com/6923650/60723980-7b2adb00-9f35-11e9-867c-65c32ba780b6.png">

Any idea on what's causing this and how to fix it?

**Comment by fabiofcferreira** [comment]
I think this solution was only valid for Chrome-based browsers. However, it has been a while so we can try to find a solution for this if anyone has come up with one.
