### ISSUE TITLE
Make URLs in the Biography hyperlinked

### ISSUE THREAD

**Issue by malikpiara** [upframe/upframe.io#201]
Right now any URL shared in the biography is not hyperlinked. Let's fix that!

**Comment by fabiofcferreira** [comment]
I'm also improving the paragraphs detection and display.

**Comment by malikpiara** [comment]
What's our status? This was kind of forgotten.

**Comment by MathisBullinger** [comment]
@malikpiara Is this something we still want to approach heuristically or should we just wait until we support Markdown which will support links anyway? IMO the latter is the way to go.

**Comment by malikpiara** [comment]
Agree with you! Markdown!
