### ISSUE TITLE
Dropdown menu closes before mouse up

### ISSUE THREAD

**Issue by MathisBullinger** [upframe/upframe.io#233]
<img width="221" alt="Screenshot 2020-02-05 at 18 54 09" src="https://user-images.githubusercontent.com/26855066/73868539-ef6d8a00-4848-11ea-8af0-bfd4e17fda03.png">

**Comment by malikpiara** [comment]
I don't understand the bug! Is it still taking place?

**Comment by MathisBullinger** [comment]
@malikpiara it is still taking place. The dropdown closes when the click starts, not when it finishes. So if you take to long to click the item (happens particularly often when using a mouse), the dropdown closes without the navigation.

![dropdown](https://user-images.githubusercontent.com/26855066/81516039-e7852080-9336-11ea-95c6-eca3e69f8e77.gif)
