### ISSUE TITLE
Transition to the lists from homepage feels weird

### ISSUE THREAD

**Issue by malikpiara** [upframe/upframe.io#240]
![2020-03-10 14 48 38](https://user-images.githubusercontent.com/6923650/76318640-4d750d80-62de-11ea-994d-35ad8da1d08c.gif)

When a user clicks on a 'list', the transition feels weird. Can we do something to smooth it out?

**Comment by malikpiara** [comment]
What this needs is a ease-in transition.

**Comment by Samson303** [comment]
On it rn
