### ISSUE TITLE
Delete old photo when new one is uploaded

### ISSUE THREAD

**Issue by ulissesferreira** [upframe/upframe.io#25]
Right now we are allowing photos of the same mentor with different extensions to stay around in our platform. This means that if a mentor upload a picture with the format: selfie.jpg and then later changes to another one called selfie.png both of these files will stay on our platform. This only happens with different extensions.

To do this we need to:
- [ ] - Save a user's photo somewhere in our DB (the file name)
- [ ] - When the user uploads a photo, get the current file name, ...
- [ ] - ... delete it,
- [ ] - and finally proceed like we are already doing

**Comment by ulissesferreira** [comment]
Let's implement this ASAP! And stop using the email as a unique identifier for the pictures! This will leak the mentors email if you inspect the picture. Let's use their UID from the DB and add the said slots there. Next release (Mentors Alpha) will have this

**Comment by SwenSchaeferjohann** [comment]
Prio label removed for now, but make sure to raise concerns and add the label again if u dont agree! 👍  
As I understand it, it would be an edge case if ppl try to add multiple pics w/ same name? Or does it break stuff for normal users? @ulissesferreira

**Comment by ulissesferreira** [comment]
@SwenSchaeferjohann did not answer because I didn't see! Everything works perfectly, the name of the files doesn't matter the problem is that different extensions (like swen.jpg, swen.png) will stay in our storage cluttering unnecessarily...

**Comment by ulissesferreira** [comment]
Update 24/02/2019

Just commited a few changes to our API that fixes a bug that made file formats with 4 chars like JPEG to not work in our profile picture. Even though they are not common this it's always a good idea to have future proof code. It also no longer leaks mentor's emails in the pictures filename which is a very nice to have. All that is missing is the deletion of older pictures which will be included in this latest batch of changes.

**Comment by ulissesferreira** [comment]
All done and handled here https://github.com/upframe/api
