### ISSUE TITLE
Change hover styling for the inputs (forms)

### ISSUE THREAD

**Issue by malikpiara** [upframe/upframe.io#260]
Let's change the styling for the hover state of every input we have at Upframe (**including the search bar**). I created a new section on Courtyard for how they should look and you can find the properties there.

Please, also throw in there a fade-out animation!

![image](https://user-images.githubusercontent.com/6923650/80416760-f3072f00-88d4-11ea-9019-6912efca7790.png)

**Comment by Samson303** [comment]
Done and pushed for all input. Need @MathisBullinger help to include edges of the search as it is not included in css parameter .input (edges of search bar are excluded from effect(

**Comment by malikpiara** [comment]
@MathisBullinger Can you wrap it up and make the searchbar also hoverable accordingly?
