### ISSUE TITLE
Different styling in the calendar buttons (courtyard vs production)

### ISSUE THREAD

**Issue by malikpiara** [upframe/upframe.io#261]
The styling related with the hover and focused state of the buttons in the calendar UI are different from what we have in Courtyard. Have a look:

- "Today" should be between "Back" and "Next".
- "Today" and "Week" should be focused.

**Courtyard (Figma File)**
![image](https://user-images.githubusercontent.com/6923650/80418686-1384b880-88d8-11ea-80f6-d4b7a9f840b1.png)

**What's currently online**
![image](https://user-images.githubusercontent.com/6923650/80418800-3f07a300-88d8-11ea-892f-5584f2d8eef4.png)

**Comment by Samson303** [comment]
Ok on it let me see if I can change the functional code of the calendar.

**Comment by Samson303** [comment]
Made more bold and less space on bottom
