### ISSUE TITLE
Information from the mentor cards doesn't show

### ISSUE THREAD

**Issue by malikpiara** [upframe/upframe.io#267]
There are multiple instances when I'm browsing Upframe and where the headline and company of the mentor disappear. Here's a screenshot:
![image](https://user-images.githubusercontent.com/6923650/80440026-21eac880-8908-11ea-97c5-ed0c70bdcb71.png)

**Comment by MathisBullinger** [comment]
@malikpiara when exactly does this happen? Do you have a way to reproduce the issue?

**Comment by malikpiara** [comment]
@MathisBullinger: I'm not entirely sure but it seems to take place whenever someone clicks on a tag. If you click on a tag, the headline of every person who has that tag disappears. Here's a gif: 
![2020-05-11 03 37 33](https://user-images.githubusercontent.com/6923650/81516645-db01c780-9338-11ea-965b-93f0bd772924.gif)
