### ISSUE TITLE
Photo uploaded on signup does not appear

### ISSUE THREAD

**Issue by malikpiara** [upframe/upframe.io#281]
When I signed up with a founder's account, I uploaded and cropped a photo. It doesn't appear on my profile now that I'm signed up:
![image](https://user-images.githubusercontent.com/6923650/81518493-88c3a500-933e-11ea-83c1-8614a6895461.png)

My account profile: https://beta.upframe.io/MalikTestify2

**Comment by MathisBullinger** [comment]
Probably fixed by [updating the image resizing service](https://github.com/upframe/resize/commit/fe555ee83be2584db44112a5dbc302106d193599).

Feel free to reopen if the issue still occurs.

**Comment by malikpiara** [comment]
It's fixed
