### ISSUE TITLE
Founders shouldn't have the ability to invite people

### ISSUE THREAD

**Issue by malikpiara** [upframe/upframe.io#284]
Unless they have special permissions, founders shouldn't be able to invite people to our platform. When using one account I created for testing, I was able to send invites to other founders. Can we fix this?

![image](https://user-images.githubusercontent.com/6923650/81613108-2a4e0380-93de-11ea-9570-5a0c20f53999.png)

**Comment by MathisBullinger** [comment]
Yeah, that's how I understood we discussed the invite behavior: founders can only invite other founders and mentors can choose whether to invite someone as a founder or as a mentor.

But sure, I can remove the ability for founder accounts.

> Unless they have special permissions

What would those permissions be? Can you give a specific founder the permission to invite other founders? If so, who can give this permission?

**Comment by malikpiara** [comment]
For now, I would make it so that only mentors can invite people.

Because of a supply/demand issue, we have to come up with ways to balance
the mentor and founders using our perform in a Early Stage.
