### ISSUE TITLE
Change meta tag

### ISSUE THREAD

**Issue by malikpiara** [upframe/upframe.io#293]
When someone shares a profile of a user on the internet, the preview still includes our old name, "Upframe Connect" instead of "Upframe". Can we change that?

![image](https://user-images.githubusercontent.com/6923650/82802402-1d6ded00-9e7f-11ea-8b61-97f71c2fb60d.png)

`<meta property="og:site_name" content="Upframe Connect">`

**Comment by malikpiara** [comment]
**Also found this:**

![image](https://user-images.githubusercontent.com/6923650/82802822-ccaac400-9e7f-11ea-8f4e-148283096f89.png)

We're not using fullstory anymore:

![image](https://user-images.githubusercontent.com/6923650/82803105-3e830d80-9e80-11ea-95a1-3999932d1b48.png)

We're also not using the Roboto font:
![image](https://user-images.githubusercontent.com/6923650/82803148-4f338380-9e80-11ea-8c6e-ec6241bbdae8.png)


The Upframe icon here is outdated and should be replaced:
`<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">`
https://upframe.io/apple-touch-icon.png

**Comment by MathisBullinger** [comment]
Actually, we are using the Roboto font for the Google sign-in button, as demanded by [Google's branding guidelines](https://developers.google.com/identity/branding-guidelines).

**Comment by malikpiara** [comment]
lol, do we have to? Is this affecting our performance in any way that would
be relevant?

**Comment by MathisBullinger** [comment]
There are ways to minimize any potential performance impacts it could have (e.g. lazy loading and only loading the characters needed). 
But if we want to improve performance, this is really not the place to start. In most cases, the font will be served from the browser cache. Even if it isn't, almost always the font will be done loading before any content of our page has been rendered. Compared to some of our API requests, the size of the font is tiny. But when we have put some work into optimizing the performance of the page to a point where the font request actually matters—as stated above—we can look into minimizing that impact.
