### ISSUE TITLE
Make the profile photo clickable on the conversations

### ISSUE THREAD

**Issue by malikpiara** [upframe/upframe.io#309]
Let's make the profile photo clickable in every single instance:
![image](https://user-images.githubusercontent.com/6923650/90320837-452f9700-df3c-11ea-983f-58a93527e60c.png)

**Comment by MathisBullinger** [comment]
Clickable to do what? Open the user's profile, start a conversation with them, open a context menu?

**Comment by malikpiara** [comment]
Open the user profile, just like "View profile"
