### ISSUE TITLE
Mentor cannot add slots to the calendar

### ISSUE THREAD

**Issue by malikpiara** [upframe/upframe.io#348]
![image](https://user-images.githubusercontent.com/6923650/98049269-42e82500-1e27-11eb-8d5d-249333a2032a.png)

This person wasn't able to slots to the calendar: https://upframe.io/GoncaloMartinsRibeir

He doesn't have the calendar connected with Google and had his account converted from a founder account to mentor account.

**Comment by MathisBullinger** [comment]
He needs to log out & in once for the role change to properly take effect. If the issue still happens after that please reopen the issue
