### ISSUE TITLE
Login reportedly not working for one person

### ISSUE THREAD

**Issue by malikpiara** [upframe/upframe.io#351]
Someone is trying to login via mobile on **Safari**. As they hit the login button, they go back to the homepage without being logged in. Here's a video: https://www.dropbox.com/s/ulp130eduky7pae/Image%20from%20iOS.mov?dl=0

Profile: https://upframe.io/CarlosPestana

**Comment by malikpiara** [comment]
[Carlos](https://upframe.io/CarlosPestana) told me he was logged in. He got a message that there was a product update and that he needed to refresh the page. After refreshing that's when he reports not being able to login. It also happens in desktop apparently.

**Comment by MathisBullinger** [comment]
probably fixed by [this commit](https://github.com/upframe/graphapi/commit/03aee580c8f2219e668a4ccee6d34b184ae12231)
