### ISSUE TITLE
Make people who sign up with an existing account log in instead

### ISSUE THREAD

**Issue by malikpiara** [upframe/upframe.io#361]
![image](https://user-images.githubusercontent.com/6923650/98462919-a4a1e980-21af-11eb-8b3a-684f5bd1d06b.png)

When people try to sign up with Google and they already have an account, they get a message saying that they already have an account. Can we make it so that they login automatically when they try to create an account?

**Comment by MathisBullinger** [comment]
implemented on the `ref/google` branch
