### ISSUE TITLE
Mentor cards are not updating biography or headline

### ISSUE THREAD

**Issue by malikpiara** [upframe/upframe.io#374]
When someone updates their biography or headline, the mentor card still shows the old information.

**Steps to replicate:**
1. Go to Upframe.io
2. Change profile bio and headline on the settings page.
3. Visit the homepage or a space.

**What we can see in the card**
![image](https://user-images.githubusercontent.com/6923650/109246676-93bac980-77da-11eb-9d2b-bb51de23eea7.png)

**Updated Information**
![image](https://user-images.githubusercontent.com/6923650/109246521-55250f00-77da-11eb-9754-5f73234fbc83.png)

**Comment by malikpiara** [comment]
@MathisBullinger it turns out the bug only seems to be related with the homepage. Inside the Upframe community space, my card information is updated. That is not the case on the homepage.

**Comment by MathisBullinger** [comment]
See [comment](https://github.com/upframe/upframe.io/issues/375#issuecomment-788657996) on #375
