### ISSUE TITLE
Option to hide profile from the homepage is not working

### ISSUE THREAD

**Issue by malikpiara** [upframe/upframe.io#375]
If someone has their profile highlighted in the homepage, changing the settings doesn't change the homepage.
Their profile is still featured even when they enable the option to hide their profile.

My profile, for instance, is supposed to be hidden but you can still see it on the homepage:
![image](https://user-images.githubusercontent.com/6923650/109527821-00201c00-7aac-11eb-8db2-b04fb5842ae2.png)

### Steps to replicate

1. Go to settings/account settings.
2. Navigate to the the Privacy section on the bottom of the page.
3. Disable the option 'Hide my profile from the homepage.'
4. Refresh the page.
5. Enable the option 'Hide my profile from the homepage.'
6. Refresh the page.

**Comment by malikpiara** [comment]
@MathisBullinger This is an important issue to address because we're onboarding 3 new organisations this week. One aims to use a space privately. In case someone disables the "hide my profile from the homepage" option by mistake, they might not be able to revert it.

**Comment by MathisBullinger** [comment]
This issue and #374 were due to an error in the caching service. I think it's fixed now. Otherwise, please reopen the issue. Keep in mind that you might have to reload the page for the change to be visible in the frontend (SW cache).

**Comment by malikpiara** [comment]
When I try to add a profile back to the homepage by unticking the box, the profile is not added back. Tried viewing Upframe in different devices and browsers to account for my cache. Used this profile: https://beta.upframe.io/malik
