### ISSUE TITLE
(Urgent) New Booking Module has wrong day of the week

### ISSUE THREAD

**Issue by malikpiara** [upframe/upframe.io#376]
![image](https://user-images.githubusercontent.com/6923650/109551288-45eadd80-7ac8-11eb-93fa-217d9f9e95e9.png)

Can't believe I miss this but the new booking module is displaying the 2nd of March as a Wednesday instead of a Tuesday and so on. I don't know whether the problem is new but my guess is that this was always here and we didn't notice.

**Comment by MathisBullinger** [comment]
The bug was introduced in the new booking module

<img width="550" alt="Screenshot 2021-03-02 at 07 54 37" src="https://user-images.githubusercontent.com/26855066/109610156-a90e5b80-7b2c-11eb-987a-ac705e2571d3.png">
