### ISSUE TITLE
Non critical asset prefetching

### ISSUE THREAD

**Issue by ulissesferreira** [upframe/upframe.io#43]
Using this with #42 we can make sure that the website's experience remains smooth while different packages are fetched. The idea is that while the user is on one page we have already prefetched the next ones. 

If we implement this correctly with #42 and #17 we will have the best possible experience

**Comment by fabiofcferreira** [comment]
I have already implemented some of those strategies in our index.html file, so I think this issue should be closed, until further need for discussion.
