### ISSUE TITLE
People - Fix popup

### ISSUE THREAD

**Issue by malikpiara** [upframe/upframe.io#92]
<img width="1440" alt="screen shot 2019-01-18 at 21 31 42" src="https://user-images.githubusercontent.com/6923650/51414058-ff94c780-1b68-11e9-821d-562780c3ae12.png">
Correct styling of the forms is on Zeplin

**Comment by ulissesferreira** [comment]
We already have the styling ready but the positions are not perfect for mobile. We need this ASAP (Mentors Alpha)

**Comment by SwenSchaeferjohann** [comment]
for now, priority label removed, but feel free to add it again or raise concerns if u don't think so! We are all tryna learn! 💯

**Comment by fabiofcferreira** [comment]
In my opinion, it is possible to make some good adjustments on the mentor popup (**mobile**). However, I think it's such a confined space so I think this is a priority to design (/cc @malikpiara, @SwenSchaeferjohann ).

Let me know your thoughts as soon as you can.
