### ISSUE TITLE
People - Fix distance between tags

### ISSUE THREAD

**Issue by malikpiara** [upframe/upframe.io#94]
<img width="1440" alt="screen shot 2019-01-19 at 13 26 18" src="https://user-images.githubusercontent.com/6923650/51427269-de29ef00-1bed-11e9-966d-7471d9ce3375.png">
The distance between the tags is the same distance between the calendar slots. The 'request' button should have the same width and height as the calendar slots by the way!

**Comment by fabiofcferreira** [comment]
Slots and tags margins are the same. So I guess there's nothing to do about that.
