### ISSUE TITLE
Uploading large files silently fails

### ISSUE THREAD

**Issue by ulissesferreira** [upframe/upframe.io#97]
Bug was first detected by Mariana and was successfully replicated by me. I was successful when uploading a photo of 961 KB but the same process failed for a photo with a whopping 4.65 MB. We need to discuss this behaviour because whether we want to accept it or not we can't silently fail on the user.

I believe the limit to this upload is set in the API. Should work perfectly with Malik for now but for our next version we need to get this sorted.

**Comment by SwenSchaeferjohann** [comment]
When I remove my picture and upload another one <5mb it doesnt show up; also the mini profile icon doesnt update; 
When I try to upload a bigger pic >5mb it still seems to fail. @ulissesferreira @fabiofcferreira
