### ISSUE TITLE
Limit text fields correctly

### ISSUE THREAD

**Issue by ulissesferreira** [upframe/upframe.io#99]
Right now if we surpass our DB's field limit the program will not crash nor will it ever display a error. What happens next is that the saved information is incomplete and may even break the website! An example of this is when you add too much expertise tags and thanks to the stringify method they are saved in a specific format. If this information is too big then when we return it to our frontend, JSON.parse() will fail and crash the whole interaction (You can successfully replicate this. Just add a lot of expertise tags).

Due to the fact that this is an app breaking bug I believe it has high priority.

**Comment by SwenSchaeferjohann** [comment]
bump
